'use client';
import {useEffect,useRef,useState} from 'react';
import {FRIENDS,ISLANDS,INITIAL,neighbours,type GameSnapshot} from './world';
import type {Sky} from './engine';

function CloudIcon(){return <svg viewBox="0 0 48 34" fill="none" aria-hidden="true"><path d="M12 29C1 29 1 14 10 13C9 1 26-2 31 10C45 5 51 27 37 29Z" fill="currentColor"/><circle cx="19" cy="19" r="1.6" fill="#40566D"/><circle cx="30" cy="19" r="1.6" fill="#40566D"/><path d="M22 23Q24.5 25 27 23" stroke="#40566D" strokeWidth="1.5" strokeLinecap="round"/></svg>}
function StarIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 3.1 6.3 7 .9-5.1 4.9 1.2 6.9-6.2-3.3-6.2 3.3 1.2-6.9L2 9.2l7-.9Z" fill="currentColor"/></svg>}
function Face({color,asleep=false}:{color:string;asleep?:boolean}){return <span className={`face ${asleep?'asleep':''}`} style={{background:color}} aria-hidden="true"><i/><i/><b/></span>}
const PALETTE=['#fff9ec','#ffd3e2','#b9e4e9','#dcd1f5'];
export function CloudGame(){
 const worldRef=useRef<HTMLDivElement>(null),markerRefs=useRef<(HTMLButtonElement|null)[]>([]),engine=useRef<Sky|null>(null);
 const [s,setS]=useState<GameSnapshot>(INITIAL),[ready,setReady]=useState(false),[error,setError]=useState(''),[muted,setMuted]=useState(false),[color,setColor]=useState(0),[help,setHelp]=useState(false);
 useEffect(()=>{let cancelled=false;void import('./engine').then(({Sky})=>{if(cancelled||!worldRef.current)return;try{const sky=new Sky(worldRef.current,{update:setS,ready:()=>setReady(true),error:setError});engine.current=sky;sky.setMarkers(markerRefs.current.filter((x):x is HTMLButtonElement=>!!x));}catch(e){setError(e instanceof Error?e.message:'The 3D sky could not load.');}});return()=>{cancelled=true;engine.current?.dispose();engine.current=null;};},[]);
 const playing=s.phase==='playing',menu=s.phase==='menu',finished=s.phase==='won'||s.phase==='over',ns=neighbours(s.island);
 const start=()=>{setHelp(false);engine.current?.start();if(document.activeElement instanceof HTMLElement)document.activeElement.blur();};
 function pickColor(i:number){setColor(i);engine.current?.setColor(PALETTE[i]);}
 return <main className={`cloudhop phase-${s.phase} ${s.friends.length===3?'full-crew':''}`}>
  <div className="sky-wash"/><div className="sun-glow"/><div className="world" ref={worldRef}/>
  <header className="topbar"><button className="brand" onClick={()=>engine.current?.home()} aria-label="Cloudhop home"><CloudIcon/><span>cloudhop<span className="brand-dot">✦</span></span></button><div className="top-actions"><span className="little-label">A LITTLE SKY ADVENTURE</span><button className="icon-button" aria-label={muted?'Turn sound on':'Mute sound'} onClick={()=>{setMuted(!muted);engine.current?.mute(!muted);}}>{muted?<span>♪<s/></span>:<span>♫</span>}</button>{!menu&&!finished&&<button className="icon-button" aria-label={s.phase==='paused'?'Resume game':'Pause game'} onClick={()=>engine.current?.pause()}>{s.phase==='paused'?'▶':'Ⅱ'}</button>}<button className="icon-button" aria-label="How to play" onClick={()=>{if(playing)engine.current?.pause();setHelp(!help);}}>?</button></div></header>
  <div className="island-labels" aria-label="Floating islands">
   {ISLANDS.map((p,i)=>{const reachable=playing&&ns.includes(i)&&!s.hopping;const rain=s.storm===i;return <button ref={el=>{markerRefs.current[i]=el;}} key={p.name} className={`island-label ${reachable?'reachable':''} ${s.selected===i?'targeted':''} ${i===s.island?'current':''} ${rain?'rainy':''} ${i===0&&s.friends.length===3?'come-home':''}`} disabled={!reachable} tabIndex={reachable?0:-1} aria-label={`Hop to ${p.name}${rain?' (rain cloud)':''}`} onClick={()=>{engine.current?.jump(i);if(document.activeElement instanceof HTMLElement)document.activeElement.blur();}}><span>{i===0?'⌂':rain?'☂':'friend' in p&&!s.friends.includes(p.friend)?'♡':s.visited.includes(i)?'·':'✦'}</span>{p.name}{reachable&&<b>↗</b>}</button>;})}
  </div>
  {menu&&<section className="welcome"><span className="eyebrow"><span/> LITTLE CLOUD. BIG ADVENTURE.</span><h1>A hop, <br/>a skip, <br/><em>a little joy.</em></h1><p>Your friends fell asleep in the sky.<br/>Hop over, scoop them up, and bring<br className="desktop-br"/> the whole fluffy gang home.</p><div className="start-row"><button className="play-button" disabled={!ready||!!error} onClick={start}><span>▶</span>{ready?'Let’s hop!':'Warming up the sky…'}<small>↗</small></button><span className="play-time">90 seconds<br/>of happy little hops</span></div><div className="colour-picker"><span>Your little cloud</span>{PALETTE.map((c,i)=><button key={c} onClick={()=>pickColor(i)} aria-label={`Choose ${['vanilla','strawberry','mint','lavender'][i]} cloud`} aria-pressed={color===i} className={color===i?'picked':''} style={{background:c}}/> )}</div><a className="dream-link" href="/dream">Step inside a dream <span>LIVE WORLD MODEL ↗</span></a><div className="welcome-hint"><span className="pointer-icon">↖</span> Just tap an island. You’ll get the hang of it.</div></section>}
  {!menu&&<><section className="scoreboard" aria-label="Game score"><div className="score-pill"><StarIcon/><strong>{s.stars}</strong><span>score</span></div><div className={`timer-pill ${s.time<20?'hurry':''}`}><span className="clock-icon">◷</span><strong>{String(Math.floor(Math.ceil(s.time)/60)).padStart(1,'0')}:{String(Math.ceil(s.time)%60).padStart(2,'0')}</strong></div><div className="crew-pill"><div>{FRIENDS.map((f,i)=><Face color={s.friends.includes(i)?f.color:'#d8dce4'} asleep={!s.friends.includes(i)} key={f.name}/>)}</div><strong>{s.friends.length}<span>/3</span></strong></div></section><div className="mission"><span>{s.friends.length===3?'THE GANG’S ALL HERE':'OPERATION: CUDDLE PUDDLE'}</span><h2>{s.friends.length===3?'Bring your friends home!':'Find your three sleepy friends.'}</h2></div></>}
  {s.message&&playing&&<div className={`toast ${s.friends.length===3?'home-toast':''}`} role="status" key={s.message}><span>✦</span>{s.message}</div>}
  {s.combo>=2&&playing&&<div className="combo" key={s.combo}><strong>{s.combo}×</strong><span>HAPPY HOPS</span></div>}
  {playing&&<footer className="play-footer"><div className="instruction-chip"><span className="tiny-cloud"><CloudIcon/></span><span>{s.hopping?'Wheeeee!':'Tap a glowing island to hop'}<small>{s.friends.length===3?'Follow the rainbow back home.':'Grab stars. Wake friends. Dodge the rain.'}</small></span></div><div className="keyboard-hint"><kbd>←</kbd><kbd>→</kbd><span>choose</span><kbd>space</kbd><span>hop</span></div><button className="hop-button" disabled={s.hopping} onClick={()=>{engine.current?.jump(s.selected);if(document.activeElement instanceof HTMLElement)document.activeElement.blur();}}>Hop to {ISLANDS[s.selected].name} <span>↗</span></button></footer>}
  {menu&&<footer className="menu-footer"><span>☁ Made for your inner five-year-old.</span><div><span>3 little friends</span><i>·</i><span>9 floating islands</span><i>·</i><span>one happy home</span></div>{s.best>0&&<span>YOUR BEST <b>✦ {s.best}</b></span>}</footer>}
  {(s.phase==='paused'||help)&&<div className="modal-backdrop"><section className="modal help-modal" role="dialog" aria-modal="true" aria-label={help?'How to play':'Game paused'}><div className="modal-mascot"><CloudIcon/></div><span className="eyebrow">TAKE A LITTLE BREATHER</span><h2>{help?'Easy as one, two, whee.':'Clouds need breaks, too.'}</h2><div className="how-steps"><p><b>01</b><span><strong>Tap a glowing island</strong>Your cloud hops there. No aiming needed.</span></p><p><b>02</b><span><strong>Find Peep, Pip & Momo</strong>They’ll follow you! Bring all three home.</span></p><p><b>03</b><span><strong>Keep the happy hops going</strong>Quick hops boost your score. Rain clouds bounce you back.</span></p></div><button className="play-button" onClick={()=>{setHelp(false);if(s.phase==='paused')engine.current?.pause();}}> {menu?'Got it!':'Back to the sky'} <span>↗</span></button></section></div>}
  {finished&&<div className="modal-backdrop finish-backdrop"><section className="modal finish-modal" role="dialog" aria-modal="true" aria-label="Round complete"><div className="end-friends">{FRIENDS.map((f,i)=><Face key={f.name} color={s.friends.includes(i)?f.color:'#dee1e7'} asleep={!s.friends.includes(i)}/>)}</div><span className="eyebrow">{s.phase==='won'?'MISSION: ABSOLUTELY ADORABLE':'TIME FOR A LITTLE SUNSET'}</span><h2>{s.phase==='won'?<>The whole gang.<br/><em>One happy home.</em></>:<>A lovely little<br/><em>sky adventure.</em></>}</h2><p>{s.phase==='won'?'Peep, Pip and Momo are home for cloudberry cake. You did that.':`You found ${s.friends.length} of your 3 friends. They’re saving you a slice for next time.`}</p><div className="round-stats"><div><StarIcon/><strong>{s.stars}</strong><span>HAPPINESS POINTS</span></div><div><strong>{s.best}</strong><span>YOUR BEST</span></div></div><button className="play-button" onClick={start}>One more hop? <span>↗</span></button>{s.phase==='won'&&<a className="dream-link end-dream" href="/dream">Explore your dream island ↗</a>}<button className="text-button" onClick={()=>engine.current?.home()}>Back to the clouds</button></section></div>}
  {error&&<div className="modal-backdrop"><section className="modal" role="alert"><h2>A tiny cloud hiccup.</h2><p>{error}</p><button className="play-button" onClick={()=>window.location.reload()}>Reload the sky ↗</button></section></div>}
 </main>;
}
