'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {LingbotWorld2Model} from '@reactor-models/lingbot-world-2/core';
import {DreamSound} from './DreamSound';
import {DreamRecorder,RecordingState} from './DreamRecorder';
import './dream.css';

const PROMPT='A joyful third-person adventure game in a soft clay candy-coloured floating island garden. The same tiny vanilla-white cloud creature with pink cheeks walks along a broad mint-green grassy path toward a rainbow bridge. Pastel pink and lavender fluffy trees, smiling yellow star creatures, rounded mushrooms, small daisies, warm sunlight, soft tactile materials. Preserve the reference character and the garden identity. Navigable continuous environment, smooth camera movement, cute friendly atmosphere, no text, no UI, no overlays.';
const MISSIONS=[
 {id:'friend',icon:'♡',title:'A tiny friend',hint:'Someone fluffy, funny, or unexpectedly cute.',caption:'Met someone a little wonderful.',colour:'#f2d3dd'},
 {id:'view',icon:'❀',title:'A dreamy view',hint:'A garden, a rainbow, a lovely place to wander.',caption:'Wish you were here.',colour:'#d5e7d7'},
 {id:'magic',icon:'✦',title:'A little magic',hint:'Make a wish. Photograph a surprise you love.',caption:'A little impossible. A lot lovely.',colour:'#e6dcf2'},
] as const;
type Mission=typeof MISSIONS[number]['id'];
type Photo={id:string;src:string;mission:Mission};
type Direction='forward'|'back'|'left'|'right';
const WISHES=[
 {id:'stars',icon:'✦',name:'Star shower',prompt:'Tiny glowing pastel stars drift gently down like confetti between the pink trees. The warm sky becomes a shimmering peach sunset.'},
 {id:'flowers',icon:'❀',name:'Giant flowers',prompt:'Giant soft pink and butter-yellow daisies slowly bloom beside the path, towering gently above the small creature. Petals sway in the warm breeze.'},
 {id:'bubbles',icon:'○',name:'Bubble party',prompt:'Translucent rainbow soap bubbles float through the garden. Gentle little bubble clusters rise around the fluffy trees, reflecting the warm sunshine.'},
] as const;
const friendly=(e:unknown)=>{const t=e instanceof Error?e.message:String(e);return /429|no available capacity|no available servers/i.test(t)?'All the dream gardens are busy. Give it a moment, then try again.':t;};
const ALBUM_KEY='dream-island-album-v1';

function Cloud(){return <svg viewBox="0 0 64 48" aria-hidden="true"><path d="M17 39C1 39 1 17 15 17 15 0 42-1 43 16 62 11 66 38 48 39Z" fill="currentColor"/><ellipse cx="24" cy="25" rx="2" ry="3" fill="#6d6782"/><ellipse cx="39" cy="25" rx="2" ry="3" fill="#6d6782"/><path d="M29 30Q32 34 35 30" fill="none" stroke="#6d6782" strokeWidth="1.6" strokeLinecap="round"/><ellipse cx="19" cy="30" rx="4" ry="2" fill="#eeb9c8"/><ellipse cx="44" cy="30" rx="4" ry="2" fill="#eeb9c8"/></svg>}

export function DreamIsland(){
 const model=useRef<LingbotWorld2Model|null>(null),video=useRef<HTMLVideoElement>(null),session=useRef(0);
 const deadline=useRef(0),moveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const sound=useRef<DreamSound|null>(null),active=useRef(false),albumRef=useRef<HTMLElement>(null);
 const recorder=useRef<DreamRecorder|null>(null),recordingUrl=useRef('');
 const [recordArmed,setRecordArmed]=useState(false),[recording,setRecording]=useState(false),[recorded,setRecorded]=useState(''),[recordingExtension,setRecordingExtension]=useState('webm');
 const [status,setStatus]=useState('idle'),[error,setError]=useState(''),[chunks,setChunks]=useState(0),[action,setAction]=useState(''),[logs,setLogs]=useState<string[]>([]);
 const [photos,setPhotos]=useState<Photo[]>([]),[generated,setGenerated]=useState(false),[draft,setDraft]=useState(''),[notice,setNotice]=useState(''),[muted,setMuted]=useState(false),[seconds,setSeconds]=useState(110),[wish,setWish]=useState(''),[wishing,setWishing]=useState(false),[help,setHelp]=useState(false),[albumReady,setAlbumReady]=useState(false);
 const recordState=useRef<RecordingState>({photos:[],action:'',notice:'',wish:'',seconds:110,draft:''});
 recordState.current={photos,action,notice,wish,seconds,draft};
 const log=useCallback((s:string)=>setLogs(p=>[...p.slice(-19),s]),[]);
 const notify=useCallback((s:string)=>{setNotice(s);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),4500);},[]);
 const idle=useCallback(()=>{if(moveTimer.current)clearTimeout(moveTimer.current);const m=model.current;if(m?.getStatus()==='ready'){void m.setMoveLongitudinal({move_longitudinal:'idle'});void m.setMoveLateral({move_lateral:'idle'});void m.setLookHorizontal({look_horizontal:'idle'});}setAction('');},[]);
 const stop=useCallback(async()=>{session.current++;deadline.current=0;idle();active.current=false;sound.current?.music(false);const m=model.current;model.current=null;setStatus('idle');setGenerated(false);setWishing(false);if(video.current)video.current.srcObject=null;await m?.disconnect();},[idle]);
 useEffect(()=>{sound.current=new DreamSound();try{const saved=JSON.parse(localStorage.getItem(ALBUM_KEY)||'[]');if(Array.isArray(saved))setPhotos(saved.filter((p:Photo)=>MISSIONS.some(m=>m.id===p.mission)&&typeof p.src==='string'&&p.src.startsWith('data:image/jpeg;base64,')).slice(0,3));}catch{}setAlbumReady(true);return()=>{session.current++;if(moveTimer.current)clearTimeout(moveTimer.current);if(noticeTimer.current)clearTimeout(noticeTimer.current);void model.current?.disconnect();sound.current?.dispose();recorder.current?.stop();if(recordingUrl.current)URL.revokeObjectURL(recordingUrl.current);};},[]);
 useEffect(()=>{if(albumReady)try{localStorage.setItem(ALBUM_KEY,JSON.stringify(photos));}catch{notify('Your album is here for this visit. Download it to keep it.');}},[photos,albumReady,notify]);
 useEffect(()=>{const blur=()=>{idle();if(document.hidden)sound.current?.music(false);};const visibility=()=>{if(document.hidden)blur();else if(active.current)sound.current?.music(true);};window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);};},[idle]);
 useEffect(()=>{if(!['preparing','live'].includes(status))return;const timer=setInterval(()=>{if(!deadline.current)return;const remaining=Math.max(0,Math.ceil((deadline.current-Date.now())/1000));setSeconds(remaining);if(!remaining){void stop();notify('Your visit is over. Your postcards are yours to keep.');}},1000);return()=>clearInterval(timer);},[status,stop,notify]);

 useEffect(()=>{
  if(!generated||!recordArmed){recorder.current?.stop();recorder.current=null;setRecording(false);return;}
  if(recorder.current||!video.current)return;
  try{
   const r=new DreamRecorder();recorder.current=r;
   r.start(video.current,sound.current?.recordingTrack(),()=>recordState.current,blob=>{
    if(recordingUrl.current)URL.revokeObjectURL(recordingUrl.current);
    recordingUrl.current=URL.createObjectURL(blob);setRecorded(recordingUrl.current);setRecordingExtension(blob.type.includes('mp4')?'mp4':'webm');
    setRecording(false);setRecordArmed(false);notify('Your visit is recorded. Download your little adventure.');
   });setRecording(true);
  }catch{recorder.current=null;setRecordArmed(false);notify('Recording is unavailable in this browser. You can still collect postcards.');}
 },[generated,recordArmed,notify]);

 async function begin(){
  if(!['idle','error'].includes(status))return;
  sound.current?.unlock();sound.current?.music(true);sound.current?.welcome();active.current=true;
  setError('');setStatus('connecting');setGenerated(false);setChunks(0);setLogs([]);setWish('');setSeconds(110);const op=++session.current;
  const m=new LingbotWorld2Model();model.current=m;
  m.on('trackReceived',(name,track)=>{if(op===session.current&&name==='main_video'&&video.current){video.current.srcObject=new MediaStream([track]);void video.current.play().catch(()=>{});}});
  m.on('error',e=>{if(op===session.current)log(friendly(e.message));});
  m.on('statusChanged',state=>{if(state==='disconnected'&&op===session.current){setGenerated(false);setStatus('idle');active.current=false;deadline.current=0;sound.current?.music(false);log('Session disconnected');}});
  m.onMessage(msg=>{if(op!==session.current)return;if(msg.type!=='state')log(msg.type);if(msg.type==='chunk_complete')setChunks(c=>c+1);if(msg.type==='command_error')setError('That request did not reach the dream. Try another direction.');});
  const current=()=>op===session.current;
  try{
   const r=await fetch('/api/dream-token',{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error);if(!current())return;
   await m.connect(data.jwt);if(!current()){await m.disconnect();return;}if(m.getStatus()!=='ready')throw new Error(m.getLastError()?.message??'The garden could not connect. Try again.');
   setStatus('preparing');log('Session connected');deadline.current=Date.now()+110000;
   const seed=await fetch('/dream-seed.png');if(!seed.ok)throw new Error('The island seed could not be loaded.');
   const image=await m.uploadFile(await seed.blob(),{name:'dream-island.png'});if(!current())return;
   const imageAck=await m.setImage({image});if(!current())return;if(!imageAck)throw new Error('The reference image was not accepted.');
   const promptAck=await m.setPrompt({prompt:PROMPT});if(!current())return;if(!promptAck)throw new Error('The island prompt was not accepted.');
   await m.setRotationSpeedDeg({rotation_speed_deg:1});if(!current())return;
   await m.start();if(!current())return;if(m.getLastError())throw new Error(m.getLastError()!.message);setStatus('live');log('Start requested; awaiting generated frames');
  }catch(e){if(!current())return;await stop();setError(friendly(e));setStatus('error');}
 }
 const move=useCallback((direction:Direction)=>{
  const m=model.current;if(!generated||status!=='live'||!m)return;idle();setAction(direction==='left'?'Peeking left…':direction==='right'?'Peeking right…':direction==='forward'?'A little wander…':'A step back…');
  if(direction==='forward'||direction==='back')void m.setMoveLongitudinal({move_longitudinal:direction});else void m.setLookHorizontal({look_horizontal:direction});
  log(`Requested ${direction}`);moveTimer.current=setTimeout(idle,4000);
 },[generated,status,idle,log]);
 async function makeWish(w:typeof WISHES[number]){const m=model.current;if(!generated||!m||wishing)return;setWishing(true);setWish(w.id);idle();sound.current?.wish();notify('Wish sent. Watch what the island dreams up…');const op=session.current;try{const ack=await m.setPrompt({prompt:PROMPT+' '+w.prompt+' Preserve the walkable garden and friendly creature.'});if(op!==session.current)return;if(!ack)throw new Error('That wish did not reach the island. Try again.');log(`${w.name}: prompt accepted`);}catch(e){if(op===session.current)setError(friendly(e));}finally{if(op===session.current)setWishing(false);}}
 const photo=useCallback(()=>{const v=video.current;if(!v||!generated||!v.videoWidth||draft)return;idle();const c=document.createElement('canvas');c.width=Math.min(v.videoWidth,1200);c.height=Math.round(c.width*v.videoHeight/v.videoWidth);c.getContext('2d')?.drawImage(v,0,0,c.width,c.height);setDraft(c.toDataURL('image/jpeg',.87));sound.current?.shutter();},[generated,draft,idle]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.repeat||draft||help||e.altKey||e.ctrlKey||e.metaKey||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLAnchorElement)return;const directions:Record<string,Direction>={ArrowUp:'forward',w:'forward',ArrowDown:'back',s:'back',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};if(directions[e.key]){e.preventDefault();move(directions[e.key]);}else if(e.code==='Space'){e.preventDefault();photo();}else if(e.key==='Escape')idle();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[move,photo,idle,draft,help]);
 function keep(mission:Mission){const next=[...photos.filter(p=>p.mission!==mission),{id:crypto.randomUUID(),mission,src:draft}];const firstComplete=next.length===3&&photos.length<3;setPhotos(next);setDraft('');if(firstComplete){sound.current?.win();notify('Three little wonders. Your dream album is complete!');}else{sound.current?.collect();notify('One little wonder, safely tucked away.');}}
 function toggleSound(){const next=!muted;setMuted(next);if(sound.current){sound.current.enabled=!next;sound.current.unlock();if(active.current)sound.current.music(true);}}
 function downloadAlbum(){const c=document.createElement('canvas');c.width=1800;c.height=930;const ctx=c.getContext('2d');if(!ctx)return;ctx.fillStyle='#fbf6ed';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#685b76';ctx.font='bold 64px Trebuchet MS';ctx.fillText('Dream Island',80,110);ctx.font='24px Trebuchet MS';ctx.fillText('Three little wonders. One dream I wandered into.',83,163);Promise.all(MISSIONS.map(async(m,i)=>{const p=photos.find(p=>p.mission===m.id);const x=80+i*555,y=240;ctx.fillStyle='#ede2ec';ctx.fillRect(x-10,y-10,535,480);if(p){const im=new Image();im.src=p.src;await im.decode();const sh=im.height,sw=sh*515/365;ctx.drawImage(im,(im.width-sw)/2,0,sw,sh,x,y,515,365);}ctx.fillStyle='#685b76';ctx.font='bold 29px Trebuchet MS';ctx.fillText(m.title,x+14,y+415);ctx.font='20px Trebuchet MS';ctx.fillText(m.caption,x+14,y+448);})).then(()=>{ctx.fillStyle='#918696';ctx.font='20px Trebuchet MS';ctx.fillText('Photographed in a live world generated by LingBot World 2.',83,833);const a=document.createElement('a');a.download='my-dream-island.jpg';a.href=c.toDataURL('image/jpeg',.94);a.click();}).catch(()=>notify('The album could not export. Download each postcard instead.'));}
 const connected=['connecting','preparing','live'].includes(status),complete=photos.length===3;
 return <main className="dream-page"><div className="dream-shell"><header className="dream-header"><a className="dream-brand" href="/" onClick={()=>void stop()}><Cloud/><span>dream island<span>a tiny photo safari</span></span></a><div className="dream-header-actions"><span className="dream-event">A LITTLE WORLD, DREAMED LIVE</span><button className={`dream-record ${recordArmed?'armed':''}`} aria-pressed={recordArmed} onClick={()=>setRecordArmed(!recordArmed)}>{recording?'● Recording':recordArmed?'● Record ready':'○ Record visit'}</button><button className="dream-icon" aria-label={muted?'Turn music on':'Mute music'} onClick={toggleSound}>{muted?'♫̸':'♫'}</button><button className="dream-icon" aria-label="How to play" onClick={()=>setHelp(true)}>?</button></div></header>
 <div className="dream-layout"><section className="dream-stage"><div className={`dream-window ${generated?'is-live':''}`}><img src="/dream-seed.png" alt="A fluffy little creature exploring a pastel garden with a rainbow bridge"/><video aria-label="Live generated dream world" aria-hidden={!generated} ref={video} playsInline muted autoPlay className={generated?'visible':''} onTimeUpdate={()=>{if(chunks>0&&status==='live')setGenerated(true);}}/><div className={`dream-badge ${generated?'live':''}`}><i/>{generated?'DREAMING LIVE':'YOUR DREAM STARTS HERE'}</div>{generated&&<><div className="dream-visit">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}<span> left to wander</span></div><div className="dream-viewfinder"><i/><i/><i/><i/></div><button className="dream-camera" aria-label="Take postcard" onClick={photo}><svg viewBox="0 0 32 28" aria-hidden="true"><path d="M4 7h6l3-4h7l3 4h5v17H4Z"/><circle cx="16" cy="15" r="6"/></svg><span>SNAP A WONDER</span></button></>}
 {!generated&&<div className="dream-intro"><span>GET LOST. FIND SOMETHING LOVELY.</span><h1>A little place<br/>to be <em>wonderstruck.</em></h1><p>Wander a world that dreams as you go.<br/>Find three little wonders. Bring home a postcard.</p><button className="play-button" disabled={connected} onClick={begin}>{status==='connecting'?'Finding your island…':status==='preparing'||status==='live'?'Waking up the garden…':'Let’s wander'}<span>✦</span></button>{connected?<button className="dream-cancel" onClick={()=>void stop()}>Cancel visit</button>:<small>Movement, curiosity, and a little magic.</small>}</div>}
 {error&&<div className="dream-error" role="alert">{error}<button aria-label="Dismiss message" onClick={()=>setError('')}>×</button></div>}{action&&generated&&<div className="dream-action" role="status">{action}</div>}{draft&&<div className="dream-flash"/>}</div>
 <div className="dream-controls"><div className="dream-pad"><button aria-label="Look left" disabled={!generated} onClick={e=>{e.currentTarget.blur();move('left');}}>↶<span>Left</span></button><button aria-label="Walk forward" disabled={!generated} onClick={e=>{e.currentTarget.blur();move('forward');}}>↑<span>Wander</span></button><button aria-label="Look right" disabled={!generated} onClick={e=>{e.currentTarget.blur();move('right');}}>↷<span>Right</span></button><button aria-label="Step back" disabled={!generated} onClick={e=>{e.currentTarget.blur();move('back');}}>↓<span>Back</span></button><button aria-label="Stop moving" disabled={!generated} onClick={idle}>·<span>Stay</span></button></div><span className="dream-keyboard">Arrow keys to wander<br/><kbd>space</kbd> to take a postcard</span>{connected&&<button className="dream-end" onClick={()=>void stop()}>End visit ↗</button>}</div>
 <section className="dream-wishes"><div><span className="dream-eyebrow">A LITTLE MAGIC</span><h2>Make a wish.</h2><p>Ask the island for a little surprise.</p></div><div>{WISHES.map(w=><button key={w.id} className={wish===w.id?'selected':''} disabled={!generated||wishing} onClick={()=>void makeWish(w)}><span>{w.icon}</span>{w.name}<small>{wish===w.id?'wish sent':'wish for it ↗'}</small></button>)}</div></section></section>
 <aside className="dream-album" ref={albumRef}><div className="album-heading"><span className="dream-eyebrow">YOUR POCKET OF WONDERS</span><h2>A little souvenir.</h2><p>Find these three things.<br/>Take a photo when one makes you smile.</p><div className="album-progress"><div><i style={{width:`${photos.length/3*100}%`}}/></div><span>{photos.length} / 3</span></div></div><div className="album-cards">{MISSIONS.map((m,i)=>{const p=photos.find(p=>p.mission===m.id);return <div key={m.id} className={`album-card ${p?'collected':''}`} style={{'--card-color':m.colour} as React.CSSProperties}>{p?<a href={p.src} download={`dream-island-${m.id}.jpg`}><img src={p.src} alt={`Your postcard: ${m.title}`}/><span className="album-stamp">FOUND WITH LOVE ✓</span></a>:<div className="album-empty"><span>{m.icon}</span><small>WONDER NO. 0{i+1}</small></div>}<div className="album-caption"><span>{m.icon}</span><div><h3>{m.title}</h3><p>{p?m.caption:m.hint}</p></div>{p&&<span className="album-check">✓</span>}</div></div>;})}</div>{complete&&<div className="album-complete"><span>✦ LITTLE WONDER COLLECTOR ✦</span><p>You brought a little dream home.</p><button onClick={downloadAlbum}>Keep my album ↓</button></div>}<p className="album-footnote">Your discoveries, chosen by you.<br/>Saved in this browser. Yours to download.</p></aside></div>
 <footer className="dream-footer">{recorded&&<a className="dream-recording-download" href={recorded} download={`dream-island-playthrough.${recordingExtension}`}>Download my adventure ↓</a>}<span>Made of curiosity, soft clouds & a world model.</span><details><summary>Behind the dream ↗</summary><p>The world you explore is live video generated by Reactor’s LingBot World 2, guided by a starting image, your movement commands and wishes. The camera, music and postcard album are coded. You choose which discovery each photo represents; there is no automatic image judging. Characters and places can change unexpectedly.</p><span>{chunks} generated chunks received</span><pre>{logs.join('\n')}</pre></details></footer></div>
 {notice&&<div className="dream-notice" role="status"><span>✦</span>{notice}</div>}
 {draft&&<div className="dream-overlay" role="dialog" aria-modal="true" aria-labelledby="postcard-title" onKeyDown={e=>{if(e.key==='Escape')setDraft('');}}><div className="postcard-dialog"><button autoFocus className="dialog-close" aria-label="Discard postcard" onClick={()=>setDraft('')}>×</button><div className="draft-polaroid"><img src={draft} alt="The moment you just photographed"/><span>a little moment, just for you.</span></div><span className="dream-eyebrow">LOOK WHAT YOU FOUND</span><h2 id="postcard-title">What made you smile?</h2><p>Choose where this moment belongs in your album.</p><div className="postcard-choices">{MISSIONS.map(m=><button key={m.id} onClick={()=>keep(m.id)}><span>{m.icon}</span>{m.title}<small>{photos.some(p=>p.mission===m.id)?'replace postcard':'add to album +'}</small></button>)}</div><button className="draft-retry" onClick={()=>setDraft('')}>Keep looking</button></div></div>}
 {help&&<div className="dream-overlay" role="dialog" aria-modal="true" aria-labelledby="help-title"><div className="dream-help"><button autoFocus className="dialog-close" aria-label="Close help" onClick={()=>setHelp(false)}>×</button><Cloud/><span className="dream-eyebrow">WELCOME, LITTLE EXPLORER</span><h2 id="help-title">Follow your curiosity.</h2><ol><li><b>Wander.</b> Tap a direction or use the arrow keys. Each tap moves for a few seconds.</li><li><b>Wish.</b> Ask for stars, flowers, or bubbles. Give the dream a moment to respond.</li><li><b>Collect.</b> Tap the camera or press Space. Label your discovery and fill all three postcards.</li></ol><p>This world is being dreamed live. Sometimes it takes an unexpected turn. That’s something else to discover.</p><button className="play-button" onClick={()=>setHelp(false)}>Got it. Let’s get lost ✦</button></div></div>}
 </main>;
}
